apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smashing-app
  template:
    metadata:
      labels:
        app: smashing-app
    spec:
      containers:
      - name: smashing-container
        image: visibilityspots/smashing:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3030