//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanctionsApi.Data
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.7.2053.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class WHOLE
    {

        private WHOLEENTITY[] eNTITYField;

        private string dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY")]
        public WHOLEENTITY[] ENTITY
        {
            get
            {
                return this.eNTITYField;
            }
            set
            {
                this.eNTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITY
    {

        private object[] itemsField;

        private uint idField;

        private string typeField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        private string remarkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS", typeof(WHOLEENTITYADDRESS))]
        [System.Xml.Serialization.XmlElementAttribute("BIRTH", typeof(WHOLEENTITYBIRTH))]
        [System.Xml.Serialization.XmlElementAttribute("CITIZEN", typeof(WHOLEENTITYCITIZEN))]
        [System.Xml.Serialization.XmlElementAttribute("NAME", typeof(WHOLEENTITYNAME))]
        [System.Xml.Serialization.XmlElementAttribute("PASSPORT", typeof(WHOLEENTITYPASSPORT))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITYADDRESS
    {

        private object nUMBERField;

        private string sTREETField;

        private string zIPCODEField;

        private string cITYField;

        private string cOUNTRYField;

        private string oTHERField;

        private uint idField;

        private uint entity_idField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        /// <remarks/>
        public object NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }

        /// <remarks/>
        public string STREET
        {
            get
            {
                return this.sTREETField;
            }
            set
            {
                this.sTREETField = value;
            }
        }

        /// <remarks/>
        public string ZIPCODE
        {
            get
            {
                return this.zIPCODEField;
            }
            set
            {
                this.zIPCODEField = value;
            }
        }

        /// <remarks/>
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }

        /// <remarks/>
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }

        /// <remarks/>
        public string OTHER
        {
            get
            {
                return this.oTHERField;
            }
            set
            {
                this.oTHERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Entity_id
        {
            get
            {
                return this.entity_idField;
            }
            set
            {
                this.entity_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITYBIRTH
    {

        private string dATEField;

        private string pLACEField;

        private string cOUNTRYField;

        private uint idField;

        private uint entity_idField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        /// <remarks/>
        public string DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        public string PLACE
        {
            get
            {
                return this.pLACEField;
            }
            set
            {
                this.pLACEField = value;
            }
        }

        /// <remarks/>
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Entity_id
        {
            get
            {
                return this.entity_idField;
            }
            set
            {
                this.entity_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITYCITIZEN
    {

        private string cOUNTRYField;

        private uint idField;

        private uint entity_idField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        /// <remarks/>
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Entity_id
        {
            get
            {
                return this.entity_idField;
            }
            set
            {
                this.entity_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITYNAME
    {

        private string lASTNAMEField;

        private string fIRSTNAMEField;

        private string mIDDLENAMEField;

        private string wHOLENAMEField;

        private string gENDERField;

        private string tITLEField;

        private string fUNCTIONField;

        private string lANGUAGEField;

        private uint idField;

        private uint entity_idField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        /// <remarks/>
        public string LASTNAME
        {
            get
            {
                return this.lASTNAMEField;
            }
            set
            {
                this.lASTNAMEField = value;
            }
        }

        /// <remarks/>
        public string FIRSTNAME
        {
            get
            {
                return this.fIRSTNAMEField;
            }
            set
            {
                this.fIRSTNAMEField = value;
            }
        }

        /// <remarks/>
        public string MIDDLENAME
        {
            get
            {
                return this.mIDDLENAMEField;
            }
            set
            {
                this.mIDDLENAMEField = value;
            }
        }

        /// <remarks/>
        public string WHOLENAME
        {
            get
            {
                return this.wHOLENAMEField;
            }
            set
            {
                this.wHOLENAMEField = value;
            }
        }

        /// <remarks/>
        public string GENDER
        {
            get
            {
                return this.gENDERField;
            }
            set
            {
                this.gENDERField = value;
            }
        }

        /// <remarks/>
        public string TITLE
        {
            get
            {
                return this.tITLEField;
            }
            set
            {
                this.tITLEField = value;
            }
        }

        /// <remarks/>
        public string FUNCTION
        {
            get
            {
                return this.fUNCTIONField;
            }
            set
            {
                this.fUNCTIONField = value;
            }
        }

        /// <remarks/>
        public string LANGUAGE
        {
            get
            {
                return this.lANGUAGEField;
            }
            set
            {
                this.lANGUAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Entity_id
        {
            get
            {
                return this.entity_idField;
            }
            set
            {
                this.entity_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WHOLEENTITYPASSPORT
    {

        private string nUMBERField;

        private string cOUNTRYField;

        private uint idField;

        private uint entity_idField;

        private string legal_basisField;

        private System.DateTime reg_dateField;

        private string pdf_linkField;

        private string programmeField;

        /// <remarks/>
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }

        /// <remarks/>
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Entity_id
        {
            get
            {
                return this.entity_idField;
            }
            set
            {
                this.entity_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string legal_basis
        {
            get
            {
                return this.legal_basisField;
            }
            set
            {
                this.legal_basisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reg_date
        {
            get
            {
                return this.reg_dateField;
            }
            set
            {
                this.reg_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdf_link
        {
            get
            {
                return this.pdf_linkField;
            }
            set
            {
                this.pdf_linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programme
        {
            get
            {
                return this.programmeField;
            }
            set
            {
                this.programmeField = value;
            }
        }
    }

}